version: '3.9'

services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    depends_on:
      - backend

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
