version: '3.9'

services:
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    ports:
      - "5252:5252"
    depends_on:
      - backend

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    ports:
      - "9000-9005:9000"

  proxy:
    build: 
      context: ./proxy
      dockerfile: dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
